name: Sofia Lite CI/CD Pipeline

on:
  push:
    branches: [ main, sofia-lite-boot ]
  pull_request:
    branches: [ main, sofia-lite-boot ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Run unit tests
      run: |
        pip install -r requirements.txt
        pytest sofia_lite/tests/ -v

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run E2E tests
      run: |
        echo "E2E tests would run here"
        # python scripts/run_e2e.py

  load-tests:
    name: Load Tests
    runs-on: ubuntu-latest
    needs: e2e-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run load tests
      run: |
        echo "Load tests would run here"
        # k6 run load/k6_script.js

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [unit-tests, e2e-tests, load-tests]
    steps:
    - name: Check all jobs status
      run: |
        echo "All checks passed! PR is ready for merge."
