name: Load Testing with k6

on:
  push:
    branches: [ main, sofia-lite-boot ]
    paths: [ 'load/**', 'sofia_lite/**' ]
  pull_request:
    branches: [ main, sofia-lite-boot ]
    paths: [ 'load/**', 'sofia_lite/**' ]

jobs:
  load-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test-type: [smoke, quick]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: load/package.json
        
    - name: Install k6
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
        
    - name: Install dependencies
      working-directory: load
      run: npm ci
      
    - name: Run load test
      working-directory: load
      run: |
        echo "🚀 Running ${{ matrix.test-type }} load test..."
        k6 run --out json=results.json k6_script.js
        
    - name: Check thresholds
      working-directory: load
      run: |
        echo "📊 Checking performance thresholds..."
        P95_RESPONSE_TIME=$(grep "http_req_duration" results.json | grep "p95" | head -1 | cut -d'"' -f4 || echo "0")
        ERROR_RATE=$(grep "http_req_failed" results.json | grep "rate" | head -1 | cut -d'"' -f4 || echo "0")
        
        echo "P95 Response Time: ${P95_RESPONSE_TIME}ms"
        echo "Error Rate: ${ERROR_RATE}"
        
        if (( $(echo "$P95_RESPONSE_TIME > 1500" | bc -l) )); then
          echo "❌ P95 response time exceeds 1500ms threshold"
          exit 1
        fi
        
        if (( $(echo "$ERROR_RATE > 0.1" | bc -l) )); then
          echo "❌ Error rate exceeds 10% threshold"
          exit 1
        fi
        
        echo "✅ All performance thresholds met!"
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-results-${{ matrix.test-type }}
        path: load/results.json
        retention-days: 30
