apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sofia-lite
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/sofia-ai-464215/sofia-lite:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: GOOGLE_PROJECT_ID
          value: "sofia-ai-464215"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: latest
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: TWILIO_ACCOUNT_SID
              key: latest
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: TWILIO_AUTH_TOKEN
              key: latest
        - name: ELEVENLABS_API_KEY
          valueFrom:
            secretKeyRef:
              name: ELEVENLABS_API_KEY
              key: latest
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/credentials.json"
        volumeMounts:
        - name: google-service-account
          mountPath: "/app"
          readOnly: true
      volumes:
      - name: google-service-account
        secret:
          secretName: GOOGLE_SERVICE_ACCOUNT_KEY
