steps:
  # Build dell'immagine Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/sofia-ai-464215/sofia-repo/sofia-ai:latest'
      - '.'

  # Push dell'immagine ad Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/sofia-ai-464215/sofia-repo/sofia-ai:latest'

  # Deploy su Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sofia-ai'
      - '--image'
      - 'europe-west1-docker.pkg.dev/sofia-ai-464215/sofia-repo/sofia-ai:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '50'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'ENV=production'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'
      - '--set-secrets'
      - 'TWILIO_ACCOUNT_SID=twilio-account-sid:latest'
      - '--set-secrets'
      - 'TWILIO_AUTH_TOKEN=twilio-auth-token:latest'
      - '--set-secrets'
      - 'TWILIO_WHATSAPP_NUMBER=twilio-whatsapp-number:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8' 