services:
  core:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - firestore

  firestore:
    image: google/cloud-sdk:slim
    ports:
      - "8080:8080"
    command: ["gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:8080"]

  ngrok:
    image: wernight/ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: ["ngrok", "http", "core:8000"]
    depends_on:
      - core
