version: '3.8'

services:
  sofia-ai:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_WHATSAPP_NUMBER=${TWILIO_WHATSAPP_NUMBER}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}
      - GOOGLE_CLOUD_PROJECT=${FIRESTORE_PROJECT_ID}
    # Note: For production, use Google Cloud Service Account credentials via:
    # 1. Environment variables (recommended for Cloud Run/GKE)
    # 2. Google Cloud metadata service (automatic for GCE/Cloud Run)
    # 3. If using file-based credentials, create keys directory and mount properly
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sofia-network

  # Reverse proxy per HTTPS
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sofia-ai
    restart: unless-stopped
    networks:
      - sofia-network

  # Firestore Emulator per development
  firestore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    command: gcloud emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=sofia-ai-464215
    networks:
      - sofia-network

networks:
  sofia-network:
    driver: bridge 