# msg catalogue – minimal, estendibile
_MSG = {
    "greet_intro": {
        "it": "Ciao! Sono Sofia dello Studio Immigrato. Come posso aiutarti?",
        "en": "Hello! I'm Sofia from Studio Immigrato. How can I help you?",
        "fr": "Bonjour ! Je suis Sofia du Studio Immigrato. Comment puis‑je vous aider ?",
        "es": "¡Hola! Soy Sofia del Studio Immigrato. ¿En qué puedo ayudarte?",
        "ar": "مرحبًا! أنا صوفيا من ستوديو إيمّيغرَاتو. كيف يمكنني مساعدتك؟",
        "hi": "नमस्ते! मैं सोफिया, Studio Immigrato से। मैं आपकी कैसे मदद कर सकती हूँ?",
        "ur": "سلام! میں صوفیہ ہوں Studio Immigrato سے۔ میں آپ کی کیسے مدد کر سکتی ہوں؟",
        "bn": "হ্যালো! আমি সোফিয়া, Studio Immigrato থেকে। আপনাকে কীভাবে সাহায্য করতে পারি?",
        "wo": "Asalaamaalekum! Maa ngi tudd Sofia, Studio Immigrato. Nan laa la jari?",
    },
    "ask_name": {
        "it": "Piacere! Come ti chiami?",
        "en": "Nice to meet you, what's your name?",
        "fr": "Enchanté! Comment vous appelez-vous?",
        "es": "¡Encantado! ¿Cómo te llamas?",
        "ar": "تشرفت بمقابلتك! ما اسمك؟",
        "hi": "आपसे मिलकर खुशी हुई! आपका नाम क्या है?",
        "ur": "آپ سے مل کر خوشی ہوئی! آپ کا نام کیا ہے؟",
        "bn": "আপনার সাথে দেখা করে খুশি! আপনার নাম কী?",
        "wo": "Dafa am may gis! Sa turandoo lan laa?",
    },
    "clarify_name": {
        "it": "Non ho colto il tuo nome, potresti ripeterlo?",
        "en": "I didn't catch your name, could you please repeat it?",
        "fr": "Je n'ai pas saisi votre nom, pourriez-vous le répéter?",
        "es": "No capté tu nombre, ¿podrías repetirlo?",
        "ar": "لم أفهم اسمك، هل يمكنك تكراره؟",
        "hi": "मैं आपका नाम नहीं समझ पाई, क्या आप इसे दोहरा सकते हैं?",
        "ur": "میں آپ کا نام نہیں سمجھ پائی، کیا آپ اسے دہرا سکتے ہیں؟",
        "bn": "আমি আপনার নাম বুঝতে পারিনি, আপনি কি এটি পুনরাবৃত্তি করতে পারেন?",
        "wo": "Man déggul sa turandoo, lan laa wax?",
    },
    "ask_service": {
        "it": "Quale servizio di immigrazione ti serve? Possiamo aiutarti con permessi di soggiorno, cittadinanza, ricongiungimento familiare e altre procedure.",
        "en": "What immigration service do you need? We can help you with residence permits, citizenship, family reunification and other procedures.",
        "fr": "Quel service d'immigration vous faut-il? Nous pouvons vous aider avec les permis de séjour, la citoyenneté, le regroupement familial et autres procédures.",
        "es": "¿Qué servicio de inmigración necesitas? Podemos ayudarte con permisos de residencia, ciudadanía, reunificación familiar y otros procedimientos.",
        "ar": "ما هي خدمة الهجرة التي تحتاجها؟ يمكننا مساعدتك في تصاريح الإقامة والجنسية والتجمع العائلي والإجراءات الأخرى.",
        "hi": "आपको किस प्रकार की आव्रजन सेवा की आवश्यकता है? हम आपकी निवास परमिट, नागरिकता, पारिवारिक पुनर्मिलन और अन्य प्रक्रियाओं में मदद कर सकते हैं।",
        "ur": "آپ کو کس قسم کی امیگریشن سروس کی ضرورت ہے؟ ہم آپ کی رہائشی اجازت، شہریت، خاندانی اتحاد اور دیگر طریقہ کار میں مدد کر سکتے ہیں۔",
        "bn": "আপনার কী ধরনের অভিবাসন সেবা প্রয়োজন? আমরা আপনাকে আবাসিক অনুমতি, নাগরিকত্ব, পারিবারিক পুনর্মিলন এবং অন্যান্য প্রক্রিয়ায় সাহায্য করতে পারি।",
        "wo": "Lan laa immigration service yi? Man may ndimbal ci residence permit, citizenship, family reunification ak procedures yi.",
    },
    "propose_consult": {
        "it": "Perfetto! Per assisterti al meglio, ti propongo una consulenza al costo di 60€. La consulenza può essere svolta online o in presenza. Quale preferisci?",
        "en": "Perfect! To assist you best, I propose a consultation at €60. The consultation can be done online or in person. Which do you prefer?",
        "fr": "Parfait! Pour vous assister au mieux, je vous propose une consultation à 60€. La consultation peut être faite en ligne ou en personne. Que préférez-vous?",
        "es": "¡Perfecto! Para ayudarte mejor, te propongo una consulta por 60€. La consulta puede realizarse en línea o en persona. ¿Cuál prefieres?",
        "ar": "ممتاز! لمساعدتك بشكل أفضل، أقترح عليك استشارة بـ 60 يورو. يمكن إجراء الاستشارة عبر الإنترنت أو شخصياً. أيهما تفضل؟",
        "hi": "बिल्कुल सही! आपकी सर्वोत्तम सहायता के लिए, मैं 60€ में परामर्श का प्रस्ताव देती हूं। परामर्श ऑनलाइन या व्यक्तिगत रूप से किया जा सकता है। आप किसे पसंद करते हैं?",
        "ur": "بہترین! آپ کی بہترین مدد کے لیے، میں 60€ میں مشاورت کا مشورہ دیتی ہوں۔ مشاورت آن لائن یا ذاتی طور پر کی جا سکتی ہے۔ آپ کسے ترجیح دیتے ہیں؟",
        "bn": "নিখুঁত! আপনাকে সর্বোত্তম সাহায্য করার জন্য, আমি 60€ এ পরামর্শের প্রস্তাব দিচ্ছি। পরামর্শ অনলাইন বা ব্যক্তিগতভাবে করা যেতে পারে। আপনি কোনটি পছন্দ করেন?",
        "wo": "Dafa am! Ngir may ndimbal ci yaram, maa consultation ci 60€. Consultation bi man online walla ci yaram. Lan laa gis?",
    },
    "ask_channel": {
        "it": "Ottimo! Ora ti propongo 3 slot disponibili per la tua consulenza. Quale preferisci?",
        "en": "Great! Now I'll propose 3 available slots for your consultation. Which do you prefer?",
        "fr": "Excellent! Maintenant je vous propose 3 créneaux disponibles pour votre consultation. Lequel préférez-vous?",
        "es": "¡Excelente! Ahora te propongo 3 horarios disponibles para tu consulta. ¿Cuál prefieres?",
        "ar": "ممتاز! الآن سأقترح عليك 3 مواعيد متاحة لاستشارتك. أيهما تفضل؟",
        "hi": "बहुत अच्छा! अब मैं आपकी परामर्श के लिए 3 उपलब्ध समय स्लॉट प्रस्तावित करूंगी। आप किसे पसंद करते हैं?",
        "ur": "بہترین! اب میں آپ کی مشاورت کے لیے 3 دستیاب سلاٹ تجویز کروں گی۔ آپ کسے ترجیح دیتے ہیں؟",
        "bn": "চমৎকার! এখন আমি আপনার পরামর্শের জন্য 3টি উপলব্ধ স্লট প্রস্তাব করব। আপনি কোনটি পছন্দ করেন?",
        "wo": "Dafa am! Léegi maa 3 slots yi ngir sa consultation. Lan laa gis?",
    },
    "ask_slot": {
        "it": "Perfetto! Per confermare la consulenza di 60€, ti chiedo di effettuare il pagamento all'IBAN: IT60X0542811101000000123456. Una volta effettuato il pagamento, condividi il giustificativo in questa chat.",
        "en": "Perfect! To confirm the €60 consultation, I ask you to make the payment to IBAN: IT60X0542811101000000123456. Once the payment is made, share the receipt in this chat.",
        "fr": "Parfait! Pour confirmer la consultation de 60€, je vous demande d'effectuer le paiement à l'IBAN: IT60X0542811101000000123456. Une fois le paiement effectué, partagez le reçu dans ce chat.",
        "es": "¡Perfecto! Para confirmar la consulta de 60€, te pido que hagas el pago al IBAN: IT60X0542811101000000123456. Una vez realizado el pago, comparte el recibo en este chat.",
        "ar": "ممتاز! لتأكيد الاستشارة بـ 60 يورو، أطلب منك إجراء الدفع إلى IBAN: IT60X0542811101000000123456. بمجرد إجراء الدفع، شارك الإيصال في هذه المحادثة.",
        "hi": "बिल्कुल सही! 60€ परामर्श की पुष्टि के लिए, मैं आपसे IBAN: IT60X0542811101000000123456 पर भुगतान करने के लिए कहती हूं। भुगतान होने के बाद, इस चैट में रसीद साझा करें।",
        "ur": "بہترین! 60€ مشاورت کی تصدیق کے لیے، میں آپ سے IBAN: IT60X0542811101000000123456 پر ادائیگی کرنے کے لیے کہتی ہوں۔ ادائیگی ہونے کے بعد، اس چیٹ میں رسید شیئر کریں۔",
        "bn": "নিখুঁত! 60€ পরামর্শ নিশ্চিত করার জন্য, আমি আপনাকে IBAN: IT60X0542811101000000123456 এ অর্থ প্রদান করতে বলছি। অর্থ প্রদানের পর, এই চ্যাটে রসিদ শেয়ার করুন।",
        "wo": "Dafa am! Ngir confirmation consultation 60€, maa laa payment ci IBAN: IT60X0542811101000000123456. Bi payment bi defee, partage receipt ci chat bi.",
    },
    "ask_payment": {
        "it": "Grazie! Ho ricevuto il giustificativo. La tua consulenza è confermata. Ti contatteremo presto per i dettagli.",
        "en": "Thank you! I received the receipt. Your consultation is confirmed. We'll contact you soon for details.",
        "fr": "Merci! J'ai reçu le reçu. Votre consultation est confirmée. Nous vous contacterons bientôt pour les détails.",
        "es": "¡Gracias! Recibí el recibo. Tu consulta está confirmada. Te contactaremos pronto para los detalles.",
        "ar": "شكراً لك! لقد استلمت الإيصال. استشارتك مؤكدة. سنتواصل معك قريباً للتفاصيل.",
        "hi": "धन्यवाद! मुझे रसीद मिल गई है। आपकी परामर्श की पुष्टि हो गई है। हम जल्द ही विवरण के लिए आपसे संपर्क करेंगे।",
        "ur": "شکریہ! مجھے رسید مل گئی ہے۔ آپ کی مشاورت کی تصدیق ہو گئی ہے۔ ہم جلد ہی تفصیلات کے لیے آپ سے رابطہ کریں گے۔",
        "bn": "ধন্যবাদ! আমি রসিদ পেয়েছি। আপনার পরামর্শ নিশ্চিত হয়েছে। আমরা শীঘ্রই বিস্তারিত জানার জন্য আপনার সাথে যোগাযোগ করব।",
        "wo": "Jerejef! Man gis receipt bi. Sa consultation dafa confirmé. Man may contact ci details yi.",
    },
    "confirm_booking": {
        "it": "Perfetto {name}! L'appuntamento per {slot} è confermato. Ecco il link del calendario: {calendar_url}",
        "en": "Perfect {name}! The appointment for {slot} is confirmed. Here's the calendar link: {calendar_url}",
        "fr": "Parfait {name}! Le rendez-vous pour {slot} est confirmé. Voici le lien du calendrier: {calendar_url}",
        "es": "¡Perfecto {name}! La cita para {slot} está confirmada. Aquí está el enlace del calendario: {calendar_url}",
        "ar": "ممتاز {name}! تم تأكيد الموعد لـ {slot}. إليك رابط التقويم: {calendar_url}",
        "hi": "बिल्कुल सही {name}! {slot} के लिए अपॉइंटमेंट की पुष्टि हो गई है। यहाँ कैलेंडर लिंक है: {calendar_url}",
        "ur": "بہترین {name}! {slot} کے لیے ملاقات کی تصدیق ہو گئی ہے۔ یہاں کیلنڈر کا لنک ہے: {calendar_url}",
        "bn": "নিখুঁত {name}! {slot} এর জন্য অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে। এখানে ক্যালেন্ডার লিংক: {calendar_url}",
        "wo": "Dafa am {name}! Appointment bi ci {slot} dafa confirmé. Calendar link: {calendar_url}",
    },
    "route_active_app": {
        "it": "Ciao! Vedo che sei un cliente attivo. Per informazioni sulla tua pratica, ti consiglio di utilizzare l'app Studio Immigrato.",
        "en": "Hello! I see you're an active client. For information about your case, I recommend using the Studio Immigrato sofia_lite.",
        "fr": "Bonjour! Je vois que vous êtes un client actif. Pour des informations sur votre dossier, je recommande d'utiliser l'application Studio Immigrato.",
        "es": "¡Hola! Veo que eres un cliente activo. Para información sobre tu caso, te recomiendo usar la aplicación Studio Immigrato.",
        "ar": "مرحباً! أرى أنك عميل نشط. للحصول على معلومات حول قضيتك، أوصي باستخدام تطبيق Studio Immigrato.",
        "hi": "नमस्ते! मैं देख रही हूं कि आप एक सक्रिय ग्राहक हैं। आपके मामले की जानकारी के लिए, मैं Studio Immigrato ऐप का उपयोग करने की सलाह देती हूं।",
        "ur": "ہیلو! میں دیکھ رہی ہوں کہ آپ ایک فعال کلائنٹ ہیں۔ آپ کے کیس کی معلومات کے لیے، میں Studio Immigrato ایپ استعمال کرنے کی تجویز دیتی ہوں۔",
        "bn": "হ্যালো! আমি দেখছি আপনি একজন সক্রিয় গ্রাহক। আপনার মামলার তথ্যের জন্য, আমি Studio Immigrato অ্যাপ ব্যবহার করার পরামর্শ দিচ্ছি।",
        "wo": "Salam! Man gis nga client actif laa. Ngir information ci sa cas, maa laa Studio Immigrato sofia_lite.",
    },
    "clarify": {
        "it": "Mi dispiace, non ho capito bene. Puoi ripetere o spiegare meglio cosa ti serve?",
        "en": "I'm sorry, I didn't understand well. Can you repeat or explain better what you need?",
        "fr": "Je suis désolé, je n'ai pas bien compris. Pouvez-vous répéter ou mieux expliquer ce dont vous avez besoin?",
        "es": "Lo siento, no entendí bien. ¿Puedes repetir o explicar mejor qué necesitas?",
        "ar": "عذراً، لم أفهم جيداً. هل يمكنك التكرار أو شرح ما تحتاجه بشكل أفضل؟",
        "hi": "माफ़ कीजिए, मैं अच्छी तरह समझ नहीं पाई। क्या आप दोहरा सकते हैं या बेहतर समझा सकते हैं कि आपको क्या चाहिए?",
        "ur": "معذرت، میں اچھی طرح سمجھ نہیں پائی۔ کیا آپ دہرا سکتے ہیں یا بہتر طور پر سمجھا سکتے ہیں کہ آپ کو کیا چاہیے؟",
        "bn": "দুঃখিত, আমি ভালভাবে বুঝতে পারিনি। আপনি কি পুনরাবৃত্তি করতে পারেন বা আরও ভালভাবে ব্যাখ্যা করতে পারেন যে আপনার কী প্রয়োজন?",
        "wo": "Nga yéex, man déggul. Lan laa wax walla fass?",
    },
    "abuse_close": {
        "it": "Il tuo linguaggio viola la nostra politica. Questa conversazione è ora chiusa.",
        "en": "Your language violates our policy. This conversation is now closed.",
        "fr": "Votre langage viole notre politique. Cette conversation est maintenant fermée.",
        "es": "Tu lenguaje viola nuestra política. Esta conversación está ahora cerrada.",
        "ar": "لغتك تنتهك سياستنا. هذه المحادثة مغلقة الآن.",
        "hi": "आपकी भाषा हमारी नीति का उल्लंघन करती है। यह बातचीत अब बंद है।",
        "ur": "آپ کی زبان ہماری پالیسی کی خلاف ورزی کرتی ہے۔ یہ گفتگو اب بند ہے۔",
        "bn": "আপনার ভাষা আমাদের নীতির লঙ্ঘন করে। এই কথোপকথন এখন বন্ধ।",
        "wo": "Sa wax dafa violation ci sunu politique. Conversation bi léegi dafa fermé.",
    },
    "service_excluded": {
        "it": "Mi dispiace, non posso aiutarti con questo tipo di richiesta. Contatta direttamente lo Studio Immigrato.",
        "en": "I'm sorry, I cannot help you with this type of request. Please contact Studio Immigrato directly.",
        "fr": "Je suis désolé, je ne peux pas vous aider avec ce type de demande. Contactez directement Studio Immigrato.",
        "es": "Lo siento, no puedo ayudarte con este tipo de solicitud. Contacta directamente a Studio Immigrato.",
        "ar": "عذراً، لا يمكنني مساعدتك في هذا النوع من الطلبات. اتصل بـ Studio Immigrato مباشرة.",
        "hi": "माफ़ कीजिए, मैं इस प्रकार के अनुरोध में आपकी मदद नहीं कर सकती। कृपया सीधे Studio Immigrato से संपर्क करें।",
        "ur": "معذرت، میں اس قسم کی درخواست میں آپ کی مدد نہیں کر سکتی۔ براہ کرم براہ راست Studio Immigrato سے رابطہ کریں۔",
        "bn": "দুঃখিত, আমি এই ধরনের অনুরোধে আপনাকে সাহায্য করতে পারি না। অনুগ্রহ করে সরাসরি Studio Immigrato-এর সাথে যোগাযোগ করুন।",
        "wo": "Nga yéex, man may ndimbal ci lii. Contact Studio Immigrato ci yaram.",
    },
    "payment_confirmed": {
        "it": "Perfetto! Ho ricevuto il giustificativo di pagamento. La tua consulenza è confermata. Ti invierò presto il link del calendario.",
        "en": "Perfect! I received the payment receipt. Your consultation is confirmed. I'll send you the calendar link soon.",
        "fr": "Parfait! J'ai reçu le reçu de paiement. Votre consultation est confirmée. Je vous enverrai bientôt le lien du calendrier.",
        "es": "¡Perfecto! Recibí el recibo de pago. Tu consulta está confirmada. Te enviaré pronto el enlace del calendario.",
        "ar": "ممتاز! لقد استلمت إيصال الدفع. استشارتك مؤكدة. سأرسل لك رابط التقويم قريباً.",
        "hi": "बिल्कुल सही! मुझे भुगतान की रसीद मिल गई है। आपकी परामर्श की पुष्टि हो गई है। मैं जल्द ही कैलेंडर लिंक भेजूंगी।",
        "ur": "بہترین! مجھے ادائیگی کی رسید مل گئی ہے۔ آپ کی مشاورت کی تصدیق ہو گئی ہے۔ میں جلد ہی کیلنڈر کا لنک بھیجوں گی۔",
        "bn": "নিখুঁত! আমি অর্থ প্রদানের রসিদ পেয়েছি। আপনার পরামর্শ নিশ্চিত হয়েছে। আমি শীঘ্রই ক্যালেন্ডার লিংক পাঠাব।",
        "wo": "Dafa am! Man gis payment receipt bi. Sa consultation dafa confirmé. Man may calendar link ci gannaaw.",
    },
    "payment_invalid": {
        "it": "Il giustificativo non sembra valido. Assicurati che contenga l'IBAN corretto (IT60X0542811101000000123456) e l'importo di 60€. Riprova.",
        "en": "The receipt doesn't seem valid. Make sure it contains the correct IBAN (IT60X0542811101000000123456) and amount of 60€. Try again.",
        "fr": "Le reçu ne semble pas valide. Assurez-vous qu'il contient l'IBAN correct (IT60X0542811101000000123456) et le montant de 60€. Réessayez.",
        "es": "El recibo no parece válido. Asegúrate de que contenga el IBAN correcto (IT60X0542811101000000123456) y el importe de 60€. Inténtalo de nuevo.",
        "ar": "الإيصال لا يبدو صحيحاً. تأكد من أنه يحتوي على IBAN الصحيح (IT60X0542811101000000123456) والمبلغ 60 يورو. حاول مرة أخرى.",
        "hi": "रसीद मान्य नहीं लगती। सुनिश्चित करें कि इसमें सही IBAN (IT60X0542811101000000123456) और 60€ की राशि है। पुनः प्रयास करें।",
        "ur": "رسید درست نہیں لگتی۔ یقینی بنائیں کہ اس میں صحیح IBAN (IT60X0542811101000000123456) اور 60€ کی رقم ہے۔ دوبارہ کوشش کریں۔",
        "bn": "রসিদ বৈধ বলে মনে হচ্ছে না। নিশ্চিত করুন যে এতে সঠিক IBAN (IT60X0542811101000000123456) এবং 60€ এর পরিমাণ রয়েছে। আবার চেষ্টা করুন।",
        "wo": "Receipt bi dafa amul. Gis IBAN bu am (IT60X0542811101000000123456) ak 60€. Jéemaat.",
    },
    "payment_error": {
        "it": "Errore nel processamento del giustificativo. Riprova o contatta lo studio per assistenza.",
        "en": "Error processing the receipt. Try again or contact the studio for assistance.",
        "fr": "Erreur lors du traitement du reçu. Réessayez ou contactez le studio pour obtenir de l'aide.",
        "es": "Error al procesar el recibo. Inténtalo de nuevo o contacta al estudio para obtener ayuda.",
        "ar": "خطأ في معالجة الإيصال. حاول مرة أخرى أو اتصل بالاستوديو للحصول على المساعدة.",
        "hi": "रसीद प्रसंस्करण में त्रुटि। पुनः प्रयास करें या सहायता के लिए स्टूडियो से संपर्क करें।",
        "ur": "رسید کی پروسیسنگ میں خرابی۔ دوبارہ کوشش کریں یا مدد کے لیے اسٹوڈیو سے رابطہ کریں۔",
        "bn": "রসিদ প্রক্রিয়াকরণে ত্রুটি। আবার চেষ্টা করুন বা সাহায্যের জন্য স্টুডিওর সাথে যোগাযোগ করুন।",
        "wo": "Receipt processing error. Jéemaat walla contact studio ngir ndimbal.",
    },
    "ask_payment_receipt": {
        "it": "Per favore, invia il giustificativo di pagamento come immagine in questa chat.",
        "en": "Please send the payment receipt as an image in this chat.",
        "fr": "Veuillez envoyer le reçu de paiement sous forme d'image dans ce chat.",
        "es": "Por favor, envía el recibo de pago como imagen en este chat.",
        "ar": "يرجى إرسال إيصال الدفع كصورة في هذه المحادثة.",
        "hi": "कृपया भुगतान की रसीद को इस चैट में छवि के रूप में भेजें।",
        "ur": "براہ کرم ادائیگی کی رسید کو اس چیٹ میں تصویر کے طور پر بھیجیں۔",
        "bn": "অনুগ্রহ করে অর্থ প্রদানের রসিদ এই চ্যাটে ছবি হিসাবে পাঠান।",
        "wo": "Ngalla, yor payment receipt ci image ci chat bi.",
    },
    "slot_not_understood": {
        "it": "Non ho capito quale slot preferisci. Puoi scegliere 1, 2 o 3, oppure scrivere l'orario che preferisci?",
        "en": "I didn't understand which slot you prefer. Can you choose 1, 2, or 3, or write the time you prefer?",
        "fr": "Je n'ai pas compris quel créneau vous préférez. Pouvez-vous choisir 1, 2 ou 3, ou écrire l'heure que vous préférez?",
        "es": "No entendí qué horario prefieres. ¿Puedes elegir 1, 2 o 3, o escribir la hora que prefieres?",
        "ar": "لم أفهم أي موعد تفضل. هل يمكنك اختيار 1 أو 2 أو 3، أو كتابة الوقت الذي تفضله؟",
        "hi": "मैं समझ नहीं पाई कि आप कौन सा समय पसंद करते हैं। क्या आप 1, 2, या 3 चुन सकते हैं, या अपनी पसंद का समय लिख सकते हैं?",
        "ur": "میں سمجھ نہیں پائی کہ آپ کون سا وقت پسند کرتے ہیں۔ کیا آپ 1، 2، یا 3 منتخب کر سکتے ہیں، یا اپنی پسند کا وقت لکھ سکتے ہیں؟",
        "bn": "আমি বুঝতে পারিনি আপনি কোন সময় পছন্দ করেন। আপনি কি 1, 2, বা 3 বেছে নিতে পারেন, বা আপনার পছন্দের সময় লিখতে পারেন?",
        "wo": "Man déggul lan laa slot. Lan laa 1, 2 walla 3, walla wax sa yaram?",
    },
    "booking_failed": {
        "it": "Mi dispiace, non sono riuscita a prenotare l'appuntamento. Riprova più tardi o contatta lo studio.",
        "en": "I'm sorry, I couldn't book the appointment. Try again later or contact the studio.",
        "fr": "Je suis désolé, je n'ai pas pu réserver le rendez-vous. Réessayez plus tard ou contactez le studio.",
        "es": "Lo siento, no pude reservar la cita. Inténtalo más tarde o contacta al estudio.",
        "ar": "عذراً، لم أتمكن من حجز الموعد. حاول مرة أخرى لاحقاً أو اتصل بالاستوديو.",
        "hi": "माफ़ कीजिए, मैं अपॉइंटमेंट बुक नहीं कर पाई। बाद में पुनः प्रयास करें या स्टूडियो से संपर्क करें।",
        "ur": "معذرت، میں ملاقات بک نہیں کر سکی۔ بعد میں دوبارہ کوشش کریں یا اسٹوڈیو سے رابطہ کریں۔",
        "bn": "দুঃখিত, আমি অ্যাপয়েন্টমেন্ট বুক করতে পারিনি। পরে আবার চেষ্টা করুন বা স্টুডিওর সাথে যোগাযোগ করুন।",
        "wo": "Nga yéex, man may book appointment bi. Jéemaat ci gannaaw walla contact studio.",
    },
    "booking_confirmed_no_calendar": {
        "it": "Perfetto {name}! L'appuntamento per {slot} è confermato. Ti contatteremo presto per i dettagli del calendario.",
        "en": "Perfect {name}! The appointment for {slot} is confirmed. We'll contact you soon for calendar details.",
        "fr": "Parfait {name}! Le rendez-vous pour {slot} est confirmé. Nous vous contacterons bientôt pour les détails du calendrier.",
        "es": "¡Perfecto {name}! La cita para {slot} está confirmada. Te contactaremos pronto para los detalles del calendario.",
        "ar": "ممتاز {name}! تم تأكيد الموعد لـ {slot}. سنتواصل معك قريباً لتفاصيل التقويم.",
        "hi": "बिल्कुल सही {name}! {slot} के लिए अपॉइंटमेंट की पुष्टि हो गई है। हम जल्द ही कैलेंडर के विवरण के लिए आपसे संपर्क करेंगे।",
        "ur": "بہترین {name}! {slot} کے لیے ملاقات کی تصدیق ہو گئی ہے۔ ہم جلد ہی کیلنڈر کی تفصیلات کے لیے آپ سے رابطہ کریں گے۔",
        "bn": "নিখুঁত {name}! {slot} এর জন্য অ্যাপয়েন্টমেন্ট নিশ্চিত হয়েছে। আমরা শীঘ্রই ক্যালেন্ডারের বিস্তারিত জানার জন্য আপনার সাথে যোগাযোগ করব।",
        "wo": "Dafa am {name}! Appointment bi ci {slot} dafa confirmé. Man may contact ci calendar details yi.",
    },
}

def T(tag: str, lang: str) -> str:
    return _MSG.get(tag, {}).get(lang, _MSG[tag]["en"]) 