# ===== ALERT MANAGER CONFIGURATION FOR SOFIA AI =====
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'sofia-ai-alerts@yourdomain.com'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/critical'
        title: 'Sofia AI Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    
    # Uncomment and configure for email alerts
    # email_configs:
    #   - to: 'admin@yourdomain.com'
    #     subject: 'CRITICAL: Sofia AI Alert - {{ .GroupLabels.alertname }}'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       {{ end }}

    # Uncomment and configure for Slack alerts
    # slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    #     channel: '#sofia-ai-alerts'
    #     title: 'Sofia AI Critical Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/warning'
        title: 'Sofia AI Warning'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}' 