name: Client Tests

on:
  pull_request:
    branches: [ main, develop, bulk-api-bootstrap ]
  push:
    branches: [ main, develop, bulk-api-bootstrap ]

jobs:
  client-tests:
    name: Client Tests (Python 3.11)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        
    - name: Run client tests
      run: |
        tox -e client311
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: client-junit
        path: reports/client-junit.xml
        retention-days: 30
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: client-coverage
        path: |
          .coverage
          htmlcov/
        retention-days: 30
