name: Deploy monitoring

on:
  push:
    paths:
      - 'monitoring/**'
jobs:
  deploy-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}
      - run: make deploy-monitor 